CREATE TABLE FREEBBS(
   SEQ NUMBER(8) PRIMARY KEY,
   BBS_NUM NUMBER(1) NOT NULL,            -- 게시판 고유번호: 2로 지정
   ID VARCHAR2(50) NOT NULL,
   REF NUMBER(8) NOT NULL,
   STEP NUMBER(8) NOT NULL,
   DEPTH NUMBER(8) NOT NULL,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   F_NAME VARCHAR2(200),               -- FILE이름
   L_NAME VARCHAR2(2000),                -- 위치이름
   F_LIKE NUMBER(8) NOT NULL,            -- FREEBBS LIKE, 기본값: 0
   WDATE DATE NOT NULL,
   PARENT NUMBER(8) NOT NULL,
   READCOUNT NUMBER(8) NOT NULL,
   DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_FREEBBS
START WITH 1 INCREMENT BY 1;

ALTER TABLE FREEBBS
ADD CONSTRAINT FK_FREEBBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);


CREATE TABLE BBSREPLE(
   SEQ NUMBER(8) PRIMARY KEY,
   BBS_NUM NUMBER(1) NOT NULL,            -- 게시판 고유번호: 1로 지정
   ID VARCHAR2(50) NOT NULL,
   REF NUMBER(8) NOT NULL,
   STEP NUMBER(8) NOT NULL,
   CONTENT VARCHAR2(4000) NOT NULL,
   WDATE DATE NOT NULL,
   DEL NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_BBSREPLE
START WITH 1 INCREMENT BY 1;


ALTER TABLE BBSREPLE ADD CONSTRAINT BBSREPLE_FK1
FOREIGN KEY (ID)
REFERENCES MEMBER(ID); 


select * from MEMBER;

select * from MEMBER;

select * from BBSREPLE


insert into MEMBER(ID, PW, NAME, GENDER, BIRTH, ADDRESS, JOB, EMAIL, IMAGE, LOG)
VALUES('harp', '1', '황혜린', 1, '1992-12-28', '서울', '백수', 'harpsong@naver.com' , '0', '0');