CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	RDATE VARCHAR2(12) NOT NULL,
	WDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_CALENDAR
START WITH 1 INCREMENT BY 1;

ALTER TABLE CALENDAR 
ADD CONSTRAINT FK_CALENDAR_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM CALENDAR;