CREATE TABLE SIST_VOTER(
	VOTERID NUMBER NOT NULL,
	POLLID NUMBER,
	POLLSUBID NUMBER NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT SIST_VOTER_PK PRIMARY KEY("VOTERID")
);


CREATE SEQUENCE SIST_VOTER_SEQ 
START WITH 1 INCREMENT BY 1;

ALTER TABLE SIST_VOTER ADD CONSTRAINT SIST_VOTER_FK
FOREIGN KEY ("POLLID")
REFERENCES SIST_POLL("POLLID")

ALTER TABLE SIST_VOTER ADD CONSTRAINT SIST_VOTER_FK2
FOREIGN KEY ("POLLSUBID")
REFERENCES SIST_POLLSUB("POLLSUBID")

ALTER TABLE SIST_VOTER ADD CONSTRAINT SIST_VOTER_FK3
FOREIGN KEY ("ID")
REFERENCES MEMBER("ID")