CREATE TABLE SIST_POLL(
	POLLID NUMBER NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	QUESTION VARCHAR2(1000) NOT NULL,
	SDATE DATE NOT NULL,
	EDATE DATE NOT NULL,
	ITEMCOUNT NUMBER NOT NULL,
	POLLTOTAL NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT SIST_POLL_PK PRIMARY KEY("POLLID")
);


CREATE SEQUENCE SIST_POLL_SEQ 
START WITH 1 INCREMENT BY 1;

ALTER TABLE SIST_POLL ADD CONSTRAINT SIST_POLL_FK
FOREIGN KEY("ID")
REFERENCES MEMBER("ID");
